#2023-06-01 07:30
name: Android CI

on:
  workflow_dispatch:
#  pull_request:
#    paths-ignore:
#      - '.idea/**'
#      - '.gitattributes'
#      - '.github/**.json'
#      - '.gitignore'
#      - '.gitmodules'
#      - '**.md'
#      - 'LICENSE'
#      - 'NOTICE'

env:
  PRG_NAME: "finamp"
  PRG_VERSION: "v0.6.15"
  TAG_NAME: "finamp"
  TAG_VERSION: "vv0.6.15"
  TAG_BUILD: "-b"
  TAG_REF: "0000000"
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  #  signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #  alias: ${{ secrets.ANDROID_ALIAS }}
  #  keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
  #  keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: deep-soft/checkout@v3

      - name: Get ref, set build version
        shell: bash
        run: |
          _ref_all_=$(git log -1 --format='%H')
          # _ref_=$(echo ${_ref_all_::7})
          _ref_org_=${{ env.TAG_REF }}
          _ref_len_="${#_ref_org_}"
          _ref_=$(echo ${_ref_all_::$_ref_len_})
          echo "TAG_REF=$_ref_" >> $GITHUB_ENV
          _build_=${{ env.TAG_BUILD }}.$_ref_
          echo "TAG_BUILD=$_build_" >> $GITHUB_ENV

      - name: Print ref, build version
        shell: bash
        run: |
          echo "REF: ${{ env.TAG_REF }}
          echo "BLD: ${{ env.TAG_BUILD }}
          echo "${{ env.TAG_NAME }}-${{ env.TAG_BUILD }}" > _tag_name_.txt

      - name: Create source archive
        continue-on-error: true
        shell: bash
        run: |
          staging="${{ env.PRG_NAME }}-src-${{ env.PRG_VERSION }}-${{ env.TAG_BUILD }}"
          touch "$staging.tar.xz"
          tar --exclude=*.tar* -cv . | xz -9 > "$staging.tar.xz"
          echo "ASSET_SRC=$staging.tar.xz" >> $GITHUB_ENV
          if [ "${{ env.DEBUG_LS }}" = "yes" ]; then
            echo "source archive name: "
            ls -l "$staging.tar.xz"
          fi

      - name: Publish src archive
        continue-on-error: true
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{ env.ASSET_SRC }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get
      # - run: flutter build apk --debug

      - name: Flutter Build
        run: flutter build apk --release

      - name: Upload Artifact
        continue-on-error: true
        uses: deep-soft/upload-artifact@v3
        with:
          name: upload-artifact
          path: |
            ./app/${{ env.PRG_NAME }}/build/outputs/apk/

      - name: Upload Artifact
        continue-on-error: true
        uses: deep-soft/upload-artifact@v3
        with:
          name: upload-artifact-all
          path: |
            ./

      - name: Copy apk from outputs/
        continue-on-error: true
        shell: bash
        run: |
          set -x
          mkdir -p signed-apk
          echo "LIST: " ./app/${{ env.PRG_NAME }}/build/outputs/apk/release/
          ls -l ./app/${{ env.PRG_NAME }}/build/outputs/apk/release/
          cp ./app/${{ env.PRG_NAME }}/build/outputs/apk/release/* ./signed-apk/
          echo "LIST: " ./signed-apk/
          ls -l ./signed-apk/
          mv ./signed-apk/{{ env.PRG_NAME }}-release-unsigned.apk ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk
          echo "LIST: " ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release.apk
          ls -l ./signed-apk/

      - uses: deep-soft/sign-android-release@master
        continue-on-error: true
        name: Sign app APK
        if: env.ANDROID_SIGNING_KEY != null
        id: sign-apk
        with:
          releaseDirectory: ./signed-apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload Artifacts
        continue-on-error: true
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/upload-artifact@v3
        with:
          name: ${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-signed.apk
          path: ${{steps.sign-apk.outputs.signedReleaseFile}}

      - name: Publish signed apk package
        continue-on-error: true
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ${{steps.sign-apk.outputs.signedReleaseFile}}
            _tag_name_.txt

      - name: Publish version build - signed apk package
        continue-on-error: true
        if: env.ANDROID_SIGNING_KEY != null
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}-${{ env.TAG_VERSION }}${{ env.TAG_BUILD }}
          files: |
            ${{steps.sign-apk.outputs.signedReleaseFile}}
            _tag_name_.txt

      - name: Publish unsigned apk package
        continue-on-error: true
        if: env.ANDROID_SIGNING_KEY == null
        uses: deep-soft/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./signed-apk/${{ env.PRG_NAME }}-${{ env.PRG_VERSION }}-release-unsigned.apk
            _tag_name_.txt
